defaults:
  - _self_
  - data: CCS_hand
  - model: default
  - optimizer: adamw
  - trainer: train
  - decode: default
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
hydra:  
  output_subdir: null  
  run:  
    dir: .
exp_dir: /data/guanjie/CuedSpeech/exp
exp_name: lip_hand_6H_multi_0128
gpus: 1
slurm_job_id:
file_path:
ckpt_path: epoch=5-loss_val=8.358474731445312.ckpt
pretrained_model_path:
transfer_frontend:
transfer_encoder:
num-nodes: 1

